### ISSUE TITLE
maxOS dotnet debug build failed 0.16.1 joystick osx

### ISSUE THREAD

**Issue by bfloydgsn** [Unity-Technologies/com.unity.tiny#5]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Versions (please complete the following information):**
 - Unity: [e.g. 2019.2.0b4]
 - Tiny: [e.g. 0.15.2]
 - Editor OS [e.g. Windows 10, MacOS X]
 - Tiny Target [e.g. wasm, asmjs, dotnet]

**Screenshots**

**Additional context**

**Comment by bfloydgsn** [comment]
not sure what happened, but all that work typing for nothing github ... here is the info instead

https://gyazo.com/ad98648f08a0fff317cdcfa362b1c9b4

Build failed. Open <a href=/Users/bfloyd/projects/solitaire/client/dots2/Library/DotsRuntimeBuild/build.log>/Users/bfloyd/projects/solitaire/client/dots2/Library/DotsRuntimeBuild/build.log</a> for more details.
##### ExitCode
1
##### Output
cp: artifacts/buildprogrambuildprogram.exe/Release/bee.exe: Permission denied
*** Tundra build failed to setup error (7.08 seconds), 0 items updated

UnityEngine.Debug:LogError(Object)
Unity.Debug:LogError(Object) (at Library/PackageCache/com.unity.entities@0.0.12-preview.33/Unity.Entities/Stubs/Unity/Debug.cs:10)
Unity.Editor.Build.BuildStepRunBee:Run(BuildContext) (at Library/PackageCache/com.unity.tiny@0.16.1-preview/Unity.Editor/Unity.Editor.Build/BuildStepRunBee.cs:83)
Unity.Editor.Build.BuildPipeline:RunBuildSteps(IReadOnlyList`1, BuildContext) (at Library/PackageCache/com.unity.tiny@0.16.1-preview/Unity.Editor/Unity.Editor.Build/BuildPipeline.cs:137)
Unity.Editor.Build.BuildPipeline:Build(BuildSettings) (at Library/PackageCache/com.unity.tiny@0.16.1-preview/Unity.Editor/Unity.Editor.Build/BuildPipeline.cs:110)
Unity.Editor.Application:Build() (at Library/PackageCache/com.unity.tiny@0.16.1-preview/Unity.Editor/Unity.Editor/Application.cs:133)
Unity.Editor.Application:BuildAndRun() (at Library/PackageCache/com.unity.tiny@0.16.1-preview/Unity.Editor/Unity.Editor/Application.cs:144)
Unity.Editor.Modes.PlayBar:PlayCommandHandler(CommandExecuteContext) (at Library/PackageCache/com.unity.tiny@0.16.1-preview/Unity.Editor/Unity.Editor.Modes/PlayBar.cs:15)
UnityEditor.CommandService:Execute(String)
Unity.Editor.Modes.PlayBar:DrawPlayBar(CommandExecuteContext) (at Library/PackageCache/com.unity.tiny@0.16.1-preview/Unity.Editor/Unity.Editor.Modes/PlayBar.cs:80)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by abdul-unity** [comment]
Hi @bfloydgsn
Please update to Tiny 0.16.1 preview https://forum.unity.com/threads/project-tiny-preview-0-16-1-c-available-and-upcoming-changes.708875/ 
let us know if you till see the issue.

**Comment by bfloydgsn** [comment]
This was 0.16.1. I'll double check this weekend
