### ISSUE TITLE
Transparency Sort Mode doesn't appear to work outside of the defaults for the Camera2D

### ISSUE THREAD

**Issue by bfloydgsn** [Unity-Technologies/com.unity.tiny#6]
**Describe the bug**
Transparency Sort Mode doesn't appear to work outside of the defaults for the Camera2D that is described and works in the tilemap blog post (unity 3d)

https://blogs.unity3d.com/2019/03/18/isometric-2d-environments-with-tilemap/

**To Reproduce**
1. create a new project tiny project
2. import some sprites from the linked demo above
3. setup basic sprites with entities and change the Transparency Sort Mode to 0,1,0
4. notice the rendering is different in the scene, game, and runtime

**Expected behavior**
rendering is correct and the same in the scene, game, and runtime

**Versions (please complete the following information):**
 - Unity:  2019.3.0
 - Tiny: 0.15.3
 - Editor OS  MacOS X
 - Tiny Target osx dotnet debug

**Screenshots**
https://gyazo.com/829c53a5acdaf7e76ebe69c07a19e25e
https://gyazo.com/6591e6d1ccb04b17a49e9b483799fd42

**Additional context**

**Comment by abdul-unity** [comment]
Hi @bfloydgsn  
Transparency Sort Mode is not supported by tiny 
to use axis sorting
Add `Camera2DAxisSort` component to the camera entity and change the sorting axis to 0,1,0 
that will give you the behavior you're seeking

**Comment by bfloydgsn** [comment]
perfect. works as intended. thanks!
